// content-calendar/react-app/src/componets/Navbar.jsx
import { NavLink } from 'react-router-dom';
import logo from '../assets/react.svg';

const Navbar = () => {

    const linkClass = ({ isActive }) =>
        isActive
          ? 'bg-black text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2'
          : 'text-white hover:bg-gray-900 hover:text-white rounded-md px-3 py-2';

  return (
    <nav className='bg-indigo-700 border-b border-indigo-500'>
        <div className='mx-auto max-w-7xl px-2 sm:px-6 lg:px-8'>
            <div className='flex flex-1 items-center justify-center md:items-stretch md:justify-start'>
                <NavLink className='flex flex-shrink-0 items-center mr-4' to='/'>
                    <img src={logo} alt="React" />
                    <span className='hidden md:block text-white text-2xl font-bold ml-2'>Home</span>
                </NavLink>
                <div className='md:ml-auto'>
              <div className='flex space-x-2'>
                <NavLink to='/' className={linkClass}>
                  Home
                </NavLink>
                <NavLink to='/content' className={linkClass}>
                  Content
                </NavLink>
                <NavLink to='/add-content' className={linkClass}>
                  Add Content
                </NavLink>
              </div>
            </div>
            </div>
        </div>

    </nav>
  )
}

export default Navbar;

// content-calendar/vue-app/src/components/NavBar.vue
<script setup>
import { RouterLink, useRoute } from 'vue-router';
import logo from '@/assets/logo.svg';

const isActiveLink = (routePath) => {
  const route = useRoute();
  return route.path === routePath;
};
</script>

<template>
  <nav class="bg-green-700 border-b border-green-500">
    <div class="mx-auto max-w-7xl px-2 sm:px-6 lg:px-8">
      <div class="flex h-20 items-center justify-between">
        <div
          class="flex flex-1 items-center justify-center md:items-stretch md:justify-start"
        >
          <!-- Logo -->
          <RouterLink class="flex flex-shrink-0 items-center mr-4" to="/">
            <img class="h-10 w-auto" :src="logo" alt="Vue Jobs" />
            <span class="hidden md:block text-white text-2xl font-bold ml-2"
              >Content Calendar</span
            >
          </RouterLink>
          <div class="md:ml-auto">
            <div class="flex space-x-2">
              <RouterLink
                to="/"
                :class="[
                  isActiveLink('/')
                    ? 'bg-green-900'
                    : 'hover:bg-gray-900 hover:text-white',
                  'text-white',
                  'px-3',
                  'py-2',
                  'rounded-md',
                ]"
                >Home</RouterLink
              >
              <RouterLink
                to="/content"
                :class="[
                  isActiveLink('/content')
                    ? 'bg-green-900'
                    : 'hover:bg-gray-900 hover:text-white',
                  'text-white',
                  'px-3',
                  'py-2',
                  'rounded-md',
                ]"
                >Content</RouterLink
              >
              <RouterLink
                to="/content/add"
                :class="[
                  isActiveLink('/content/add')
                    ? 'bg-green-900'
                    : 'hover:bg-gray-900 hover:text-white',
                  'text-white',
                  'px-3',
                  'py-2',
                  'rounded-md',
                ]"
                >Add Content</RouterLink
              >
            </div>
          </div>
        </div>
      </div>
    </div>
  </nav>
</template>
